# Generated by Django 4.0.6 on 2023-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('read_duration', models.CharField(blank=True, max_length=200)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
