# Generated by Django 4.1.3 on 2023-09-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deluxedaysapp', '0003_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Content',
        ),
    ]
