# Generated by Django 4.1.3 on 2023-09-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deluxedaysapp', '0005_guestsectioncontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='HomeContent',
        ),
    ]
