# Generated by Django 4.1.3 on 2023-09-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deluxedaysapp', '0006_rename_content_homecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestsectioncontent',
            options={'verbose_name': 'Guest Section', 'verbose_name_plural': 'Guest Section'},
        ),
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AddField(
            model_name='guestsectioncontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
