# Generated by Django 4.1.3 on 2023-09-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deluxedaysapp', '0007_alter_guestsectioncontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDescriptionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Home Description',
                'verbose_name_plural': 'Home Descriptions',
            },
        ),
    ]
