# Generated by Django 4.1.3 on 2023-09-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deluxedaysapp', '0008_homedescriptioncontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeDescriptionContent',
            new_name='Stat',
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name': 'Stat', 'verbose_name_plural': 'Stats'},
        ),
    ]
