# Generated by Django 4.1.3 on 2023-09-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deluxedaysapp', '0011_guestsectionslider_hostsectionslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('feedback', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile-pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.AlterModelOptions(
            name='hostsectionslider',
            options={'verbose_name': 'Host Slider', 'verbose_name_plural': 'Host Slider'},
        ),
    ]
