# Generated by Django 4.1.3 on 2023-09-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deluxedaysapp', '0018_aboutwhychooseus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsectioncontent',
            options={'verbose_name': 'About - Section', 'verbose_name_plural': 'About - Section'},
        ),
        migrations.AlterField(
            model_name='aboutwhychooseus',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
